# Generated by Django 3.2.7 on 2022-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
