# Generated by Django 4.0.1 on 2022-03-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_branch_user_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
