# Generated by Django 4.0.1 on 2022-03-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_phone_number_branch_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
    ]
