# Generated by Django 4.0.1 on 2022-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='adress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
