# Generated by Django 4.0.1 on 2022-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_branch_adress_alter_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='branch',
            name='schedule',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
