# Generated by Django 4.0.1 on 2022-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_branch_phone_alter_branch_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'admin'), ('florist', 'florist'), ('runner', 'runner'), ('client', 'client'), ('superuser', 'superuser')], default='client', max_length=20),
        ),
    ]
