# Generated by Django 4.0.1 on 2022-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
        migrations.DeleteModel(
            name='ConfirmCode',
        ),
    ]
