version: "3.9"
services:
  db:
    image: postgres
    ports:
     - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rejobodi6557
  web:
    build: .
    tty: true
    command:  python manage.py runserver 0.0.0.0:8000 

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

