# Generated by Django 4.0.1 on 2022-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_cart_id_cart_detail_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hight',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
