# Generated by Django 4.0.1 on 2022-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_hight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
