# Generated by Django 4.0.1 on 2022-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_hight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'processed'), (3, 'completed')], default=None, null=True),
        ),
    ]
