# Generated by Django 4.0.1 on 2022-02-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='cart',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
