# Generated by Django 4.0.1 on 2022-03-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
    ]
