# Generated by Django 4.0.1 on 2022-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='delivery',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
