# Generated by Django 4.0.1 on 2022-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('took', 'took'), ('completed', 'completed'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('completed', 'completed')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processed', 'processed'), ('completed', 'completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='complexity_of_care',
            field=models.CharField(choices=[('easy', 'easy'), ('middle', 'middle'), ('hard', 'hard')], default=None, max_length=20, null=True),
        ),
    ]
