# Generated by Django 4.0.1 on 2022-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_delivery_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_sum',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processed', 'processed'), ('completed', 'completed')], default=None, max_length=20, null=True),
        ),
    ]
