# Generated by Django 4.0.1 on 2022-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_cart_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_sum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
