# Generated by Django 4.0.1 on 2022-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_order_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='adress',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
